### ISSUE TITLE
Range is too far.

### ISSUE THREAD

**Issue by t-leith** [t-lieth/smaebeta#1]

**Comment by chunkybanana** [comment]
Please be specific. Do you want 1 block range or something?

**Comment by Thomtotom** [comment]
indeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeed

**Comment by chunkybanana** [comment]
We discussed this.

**Comment by Thomtotom** [comment]
yessssssssssssssssssssssssssssssssssss

**Comment by chunkybanana** [comment]
Fixed. Use space to attack/mine/place.
